apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devops
    app.kubernetes.io/instance: devops-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: devops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - image: superman0011/devops:latest
          imagePullPolicy: Always
          name: devops
          ports:
            - containerPort: 5000
